[tools]
"aqua:goreleaser/goreleaser" = "latest"
"aqua:nektos/act" = "latest"
go = "1.26.5"
golangci-lint = "latest"

[tasks]
build-binary = "go build -o bin/tunneller ./cmd/tunneller"
build-docker = "docker build -t tunneller:dev ."
lint = "golangci-lint run"
test = "go test ./..."

[tasks.build]
description = "Build the tunneller binary and Docker image"
depends = ["build-binary", "build-docker"]
